Add driver and example
DCC-EX/CommandStation-EX pull request #224
Opened 2022-04-02 20:49 UTC by peteGSX

PR to add the PCA/TCA9555 device driver (including updating the myHal.cpp example) as contributed by Henkk via Discord.

2022-04-03 06:44 UTC, Asbelos commented
Henkk should add his name to the copyright.

2022-11-16 23:55 UTC, JeaneLG commented on myHal.cpp_example.txt
> +
The following lines (84-92) are a duplicate resulting from copy-and-paste.

2022-11-16 23:56 UTC, JeaneLG requested changes
please change the code regarding my comment on file 'myHal.cpp_example.txt'

2022-11-17 02:59 UTC, FrightRisk commented
So this has been tested by 2 people? I don't have a board to test.

2024-01-28 20:53 UTC, peteGSX commented
This has been added in a subsequent release.

2024-01-28 20:53 UTC, closed without merging